### ISSUE TITLE
FEATURE REQUEST: New Languages

### ISSUE THREAD

**Issue by The-Kergan** [Maasq/NPC-Engineer#30] opened 2018-10-30 10:29 UTC
Adding or editing campaign-specific languages to the 'Languages Spoken' choices would be helpful for non-standard settings.

**Comment by Maasq** [comment] 2018-10-30 22:04
This is a good suggestion and should obviate the need for the 'other:' box referenced in the bug report. I have been intending to revisit this tab for a long time, and this will be part of the revamp. 

It is a big task, though, not least as it could affect every saved character that exists currently if I am not very careful. This might take some time.

Maasq

**Comment by Maasq** [comment] 2019-04-02 21:33
I have changed the language area quite significantly - adding your own languages should be easy now.

**Comment by The-Kergan** [comment] 2019-04-03 12:21
This is just fantastic. Thanks for all the hard work on the app.

**Comment by The-Kergan** [comment] 2019-04-19 18:25
Hi Maasq. Finally able to try out the languages enhancement. I can add languages, which is great. When I add a chosen language to a NPC it appears on the stat block, however, if I navigate through NPCs within a project to perhaps edit languages later, no languages are shown on the stat block. Ie they don't appear to be saved between sessions.

**Comment by Maasq** [comment] 2019-04-20 17:07
Hiya. I can't reproduce this behaviour; it works perfectly here. The obvious question - have you actually saved the NPC after adding languages to it? Not just updated your project, but saved the NPC? Cycling through NPCs loads them from HD (ie not from the project). There are operational reasons for this.

If you can, get a hold of me on Discord. It will be easier to have a back and forth chat about the issue.

**Comment by The-Kergan** [comment] 2019-04-20 17:45
I'll check on Sunday when I'm home. Almost certain that I didn't. IT Luddite I'm afraid...

⁣Best regards as ever,

John

**Comment by Maasq** [comment] 2019-04-24 22:26
That is it sorted. It was an obscure wee bug - well caught!

**Closed by Maasq** 2019-04-24 22:26 UTC
Labels: enhancement, feature request
